package com.arena.studynotes;import android.app.*;import android.os.*;import android.content.*;import android.net.*;import android.graphics.*;import android.view.*;import android.widget.*;import java.util.*;

public class EditNoteActivity extends Activity{DB db;Note n;long topic;EditText title,chapter,body,pdfName,pdfPage;String pdfUri="";static final int PDF=22,IMG=23;
 @Override public void onCreate(Bundle b){super.onCreate(b);db=new DB(this);topic=getIntent().getLongExtra("topic",1);long id=getIntent().getLongExtra("note",0);n=id>0?db.note(id):new Note();if(n.id==0){n.topicId=topic;n.tip=getIntent().getBooleanExtra("tips",false);n.pdfPage=1;}draw();}
 void draw(){LinearLayout root=Theme.root(this);root.setPadding(Theme.dp(this,16),Theme.dp(this,8),Theme.dp(this,16),0);root.addView(Theme.toolbar(this,n.id==0?"یادداشت جدید":"ویرایش یادداشت","←",v->finish(),"✓",v->save()),new LinearLayout.LayoutParams(-1,Theme.dp(this,64)));
  ScrollView sv=new ScrollView(this);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(0,Theme.dp(this,8),0,Theme.dp(this,120));sv.addView(l);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  title=Theme.input(this,"عنوان یادداشت (الزامی)",false);title.setText(n.title);l.addView(title,new LinearLayout.LayoutParams(-1,Theme.dp(this,68)));
  LinearLayout.LayoutParams gap=new LinearLayout.LayoutParams(-1,Theme.dp(this,68));gap.setMargins(0,Theme.dp(this,10),0,0);chapter=Theme.input(this,"فصل / بخش (مثلاً: فصل ۱)",false);chapter.setText(n.chapter);l.addView(chapter,gap);
  TextView old=Theme.text(this,"انتخاب سریع از فصل‌های همین موضوع",15,Theme.muted,Typeface.BOLD);old.setPadding(0,Theme.dp(this,14),0,Theme.dp(this,6));l.addView(old);HorizontalScrollView hsv=new HorizontalScrollView(this);LinearLayout chips=new LinearLayout(this);chips.setGravity(Gravity.RIGHT);hsv.addView(chips);l.addView(hsv,new LinearLayout.LayoutParams(-1,Theme.dp(this,52)));HashSet<String> seen=new HashSet<>();for(Note x:db.notes(topic,n.tip,null)){if(x.chapter!=null&&!x.chapter.isEmpty()&&seen.add(x.chapter)){TextView c=chip(x.chapter,Theme.text);chips.addView(c);c.setOnClickListener(v->chapter.setText(((TextView)v).getText()));}}
  LinearLayout pdf=card();l.addView(pdf);pdf.addView(Theme.text(this,"اتصال به کتاب PDF مرجع",23,Theme.primary,Typeface.BOLD));LinearLayout pr=new LinearLayout(this);pr.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);pdf.addView(pr);pdfName=Theme.input(this,"نام فایل یا کتاب PDF",false);pdfName.setText(n.pdfName);pr.addView(pdfName,new LinearLayout.LayoutParams(0,Theme.dp(this,68),2));pdfPage=Theme.input(this,"صفحه",false);pdfPage.setInputType(2);pdfPage.setText(n.pdfPage>0?String.valueOf(n.pdfPage):"");LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(0,Theme.dp(this,68),1);pp.setMargins(Theme.dp(this,8),0,0,0);pr.addView(pdfPage,pp);Button pick=Theme.pill(this,"📄 انتخاب PDF واقعی از حافظه",Theme.primary);LinearLayout.LayoutParams pk=new LinearLayout.LayoutParams(-1,Theme.dp(this,56));pk.setMargins(0,Theme.dp(this,10),0,0);pdf.addView(pick,pk);pdfUri=n.pdfUri==null?"":n.pdfUri;pick.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/pdf");i.addCategory(Intent.CATEGORY_OPENABLE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,PDF);});
  TextView md=Theme.text(this,"متن یادداشت با پشتیبانی Markdown",16,Theme.muted,Typeface.BOLD);md.setPadding(0,Theme.dp(this,16),0,Theme.dp(this,6));l.addView(md);body=Theme.input(this,"# تیتر\nمتن یادداشت...\nبرای بولد از **متن** استفاده کنید.",true);body.setText(n.body);l.addView(body,new LinearLayout.LayoutParams(-1,Theme.dp(this,430)));
  LinearLayout tools=new LinearLayout(this);tools.setGravity(Gravity.CENTER);tools.setPadding(Theme.dp(this,4),Theme.dp(this,8),Theme.dp(this,4),Theme.dp(this,12));tools.setBackground(Theme.border(Theme.surface,Theme.stroke,Theme.dp(this,1),Theme.dp(this,22)));root.addView(tools,new LinearLayout.LayoutParams(-1,Theme.dp(this,96)));tool(tools,"🔗\nوب",v->webLink());tool(tools,"🔖\nیادداشت",v->linkDialog(false));tool(tools,"💡\nنکته",v->linkDialog(true));tool(tools,"🖼\nعکس",v->imagePick());tool(tools,"B\nبولد",v->wrap("**","**"));}
 LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(Theme.dp(this,16),Theme.dp(this,16),Theme.dp(this,16),Theme.dp(this,16));c.setBackground(Theme.round(Theme.surface2,Theme.dp(this,22)));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,Theme.dp(this,14),0,0);c.setLayoutParams(cp);return c;}TextView chip(String s,int color){TextView c=Theme.text(this,s,15,color,Typeface.BOLD);c.setGravity(Gravity.CENTER);c.setPadding(Theme.dp(this,12),0,Theme.dp(this,12),0);c.setBackground(Theme.border(Theme.surface,Theme.stroke,Theme.dp(this,1),Theme.dp(this,16)));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,Theme.dp(this,42));p.setMargins(Theme.dp(this,6),0,0,0);c.setLayoutParams(p);return c;}
 void tool(LinearLayout t,String s,View.OnClickListener l){TextView b=Theme.text(this,s,14,Theme.text,Typeface.BOLD);b.setGravity(Gravity.CENTER);b.setBackground(Theme.round(Theme.surface2,Theme.dp(this,16)));b.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-1,1);p.setMargins(Theme.dp(this,4),0,Theme.dp(this,4),0);t.addView(b,p);}void insert(String s){int st=Math.max(body.getSelectionStart(),0);body.getText().insert(st,s);}void wrap(String a,String b){int st=body.getSelectionStart(),en=body.getSelectionEnd();if(st<0){insert(a+b);return;}body.getText().insert(en,b);body.getText().insert(st,a);} 
 void webLink(){EditText e=Theme.input(this,"https://example.com|عنوان لینک",false);new AlertDialog.Builder(this).setTitle("درج لینک وب").setView(e).setPositiveButton("درج",(d,w)->{String[]p=e.getText().toString().split("\\|",2);if(p[0].trim().isEmpty())return;insert("[web:"+p[0].trim()+"|"+(p.length>1?p[1].trim():p[0].trim())+"]");}).setNegativeButton("بستن",null).show();}
 void linkDialog(boolean tip){Dialog d=new Dialog(this);ScrollView sv=new ScrollView(this);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(Theme.dp(this,22),Theme.dp(this,22),Theme.dp(this,22),Theme.dp(this,22));l.setBackground(Theme.round(Theme.surface,Theme.dp(this,26)));sv.addView(l);d.setContentView(sv);l.addView(Theme.text(this,tip?"اتصال به نکته دیگر":"اتصال به یادداشت دیگر",25,Theme.text,Typeface.BOLD));ArrayList<Note> arr=db.notes(topic,tip,null);if(arr.isEmpty())l.addView(Theme.text(this,"موردی برای لینک‌دادن وجود ندارد.",16,Theme.muted,Typeface.BOLD));for(Note x:arr){if(x.id==n.id)continue;TextView r=Theme.text(this,x.title+"\n"+x.chapter,18,Theme.primary,Typeface.BOLD);r.setPadding(Theme.dp(this,14),Theme.dp(this,12),Theme.dp(this,14),Theme.dp(this,12));r.setBackground(Theme.round(Theme.surface2,Theme.dp(this,18)));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,Theme.dp(this,70));rp.setMargins(0,Theme.dp(this,8),0,0);l.addView(r,rp);r.setOnClickListener(v->{insert("["+(tip?"tip":"note")+":"+x.id+"|"+x.title+"]");d.dismiss();});}d.show();}
 void imagePick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,IMG);}void save(){if(title.getText().toString().trim().isEmpty()){Theme.toast(this,"عنوان لازم است");return;}n.topicId=topic;n.title=title.getText().toString().trim();n.chapter=chapter.getText().toString().trim();n.body=body.getText().toString();n.pdfName=pdfName.getText().toString().trim();try{n.pdfPage=Integer.parseInt(pdfPage.getText().toString().trim());}catch(Exception e){n.pdfPage=1;}n.pdfUri=pdfUri;db.saveNote(n);finish();}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(c==RESULT_OK&&data!=null){Uri u=data.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception e){}if(r==PDF){pdfUri=u.toString();String name=u.getLastPathSegment();pdfName.setText(name==null?"PDF":name);}if(r==IMG)insert("[img:"+u.toString()+"]");}}
}
