package com.arena.studynotes;
import android.app.*;import android.os.*;import android.content.*;import android.net.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;import org.json.*;

public class MainActivity extends Activity{DB db;LinearLayout list;EditText search;int selectedColor=0xff2f80ed;static final int EXP=9,IMP=10;
 @Override public void onCreate(Bundle b){super.onCreate(b);db=new DB(this);draw();}
 void draw(){LinearLayout root=Theme.root(this);root.setPadding(Theme.dp(this,18),Theme.dp(this,10),Theme.dp(this,18),Theme.dp(this,18));
  LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(0,Theme.dp(this,4),0,Theme.dp(this,10));top.setLayoutDirection(View.LAYOUT_RTL);root.addView(top,new LinearLayout.LayoutParams(-1,Theme.dp(this,74)));
  ImageButton theme=Theme.icon(this,Theme.dark?"☀":"☾");top.addView(theme,new LinearLayout.LayoutParams(Theme.dp(this,52),Theme.dp(this,52)));theme.setOnClickListener(v->{getSharedPreferences("s",0).edit().putBoolean("dark",!Theme.dark).apply();draw();});
  ImageButton backup=Theme.icon(this,"☁");LinearLayout.LayoutParams ibp=new LinearLayout.LayoutParams(Theme.dp(this,52),Theme.dp(this,52));ibp.setMargins(Theme.dp(this,8),0,0,0);top.addView(backup,ibp);backup.setOnClickListener(v->backupSheet());
  search=Theme.input(this,"جستجوی موضوع یا یادداشت...",false);search.setTextSize(16);search.setCompoundDrawablesWithIntrinsicBounds(null,null,new Theme.TextDrawable("⌕",Theme.primary,Theme.dp(this,22)),null);top.addView(search,new LinearLayout.LayoutParams(0,Theme.dp(this,54),1));search.setOnEditorActionListener((v,a,e)->{load(search.getText().toString().trim());Theme.hideKeyboard(this);return true;});
  TextView title=Theme.text(this,"دفترچه مرور درسی",28,Theme.text,Typeface.BOLD);title.setPadding(0,Theme.dp(this,12),0,0);root.addView(title);TextView sub=Theme.text(this,"موضوعات، یادداشت‌های Markdown، نکات علمی و PDFهای مرجع",15,Theme.muted,Typeface.BOLD);root.addView(sub);
  ScrollView sv=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(0,Theme.dp(this,8),0,Theme.dp(this,110));sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  Button add=Theme.pill(this,"＋ افزودن موضوع",Theme.primary);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,Theme.dp(this,62));ap.setMargins(0,Theme.dp(this,8),0,0);root.addView(add,ap);add.setOnClickListener(v->topicSheet(null));load(null);}
 void load(String q){list.removeAllViews();ArrayList<Topic> data=db.topics(q);if(data.isEmpty()){empty("موضوعی پیدا نشد","برای شروع، یک موضوع درسی جدید بسازید.");return;}for(Topic t:data)topicCard(t);} 
 void topicCard(Topic t){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(Theme.dp(this,18),Theme.dp(this,16),Theme.dp(this,18),Theme.dp(this,16));card.setBackground(Theme.border(Theme.soft(t.color),Theme.mix(t.color,Theme.stroke,.35f),Theme.dp(this,1),Theme.dp(this,26)));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,Theme.dp(this,14),0,Theme.dp(this,4));list.addView(card,cp);
  LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setLayoutDirection(View.LAYOUT_RTL);card.addView(row);
  TextView badge=Theme.text(this,"یادداشت ثبت شده " + t.count,13,Color.WHITE,Typeface.BOLD);badge.setGravity(Gravity.CENTER);badge.setPadding(Theme.dp(this,12),Theme.dp(this,5),Theme.dp(this,12),Theme.dp(this,5));badge.setBackground(Theme.round(t.color,Theme.dp(this,18)));row.addView(badge,new LinearLayout.LayoutParams(-2,Theme.dp(this,34)));
  Space sp=new Space(this);row.addView(sp,new LinearLayout.LayoutParams(0,1,1));ImageButton del=Theme.icon(this,"🗑");del.setImageDrawable(new Theme.TextDrawable("🗑",Theme.danger,Theme.dp(this,21)));row.addView(del,new LinearLayout.LayoutParams(Theme.dp(this,46),Theme.dp(this,46)));del.setOnClickListener(v->confirmDelTopic(t));
  TextView title=Theme.text(this,t.title,27,t.color,Typeface.BOLD);title.setPadding(0,Theme.dp(this,8),0,0);card.addView(title);TextView desc=Theme.text(this,t.desc,16,Theme.muted,Typeface.BOLD);desc.setLineSpacing(3,1);card.addView(desc);
  card.setOnClickListener(v->startActivity(new Intent(this,NoteActivity.class).putExtra("topic",t.id)));card.setOnLongClickListener(v->{topicSheet(t);return true;});}
 void empty(String a,String b){LinearLayout e=new LinearLayout(this);e.setOrientation(LinearLayout.VERTICAL);e.setGravity(Gravity.CENTER);e.setPadding(Theme.dp(this,20),Theme.dp(this,70),Theme.dp(this,20),Theme.dp(this,70));TextView ic=Theme.text(this,"📚",54,Theme.primary,Typeface.BOLD);ic.setGravity(Gravity.CENTER);e.addView(ic);TextView h=Theme.text(this,a,22,Theme.text,Typeface.BOLD);h.setGravity(Gravity.CENTER);e.addView(h);TextView m=Theme.text(this,b,16,Theme.muted,Typeface.BOLD);m.setGravity(Gravity.CENTER);e.addView(m);list.addView(e,new LinearLayout.LayoutParams(-1,-2));}
 EditText field(String h,String v){EditText e=Theme.input(this,h,false);e.setText(v==null?"":v);return e;}void topicSheet(Topic t){Dialog d=new Dialog(this);LinearLayout l=sheet(d);l.addView(Theme.text(this,t==null?"موضوع درسی جدید":"ویرایش موضوع",28,Theme.primary,Typeface.BOLD));EditText ti=field("عنوان موضوع (الزامی)",t==null?"":t.title);l.addView(ti,new LinearLayout.LayoutParams(-1,Theme.dp(this,68)));EditText de=field("توضیحات کوتاه",t==null?"":t.desc);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,Theme.dp(this,82));p.setMargins(0,Theme.dp(this,10),0,Theme.dp(this,12));l.addView(de,p);TextView lab=Theme.text(this,"انتخاب رنگ تم موضوع",17,Theme.text,Typeface.BOLD);l.addView(lab);LinearLayout colors=new LinearLayout(this);colors.setGravity(Gravity.CENTER);l.addView(colors,new LinearLayout.LayoutParams(-1,Theme.dp(this,62)));selectedColor=t==null?Theme.colorAt(0):t.color;for(int i=0;i<8;i++){int c=Theme.colorAt(i);TextView dot=Theme.text(this,"●",44,c,Typeface.BOLD);dot.setGravity(Gravity.CENTER);colors.addView(dot,new LinearLayout.LayoutParams(0,-1,1));dot.setOnClickListener(v->selectedColor=((TextView)v).getTextColors().getDefaultColor());}Button ok=Theme.pill(this,t==null?"درج موضوع جدید":"ذخیره تغییرات",Theme.primary);l.addView(ok,new LinearLayout.LayoutParams(-1,Theme.dp(this,60)));ok.setOnClickListener(v->{if(ti.getText().toString().trim().isEmpty()){Theme.toast(this,"عنوان لازم است");return;}db.saveTopic(t==null?0:t.id,ti.getText().toString().trim(),de.getText().toString().trim(),selectedColor);d.dismiss();load(null);});d.show();}
 LinearLayout sheet(Dialog d){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(Theme.dp(this,24),Theme.dp(this,24),Theme.dp(this,24),Theme.dp(this,24));l.setBackground(Theme.round(Theme.surface,Theme.dp(this,28)));d.setContentView(l);Window w=d.getWindow();return l;}
 void confirmDelTopic(Topic t){new AlertDialog.Builder(this).setTitle("حذف موضوع؟").setMessage("موضوع «"+t.title+"» همراه تمام یادداشت‌ها حذف می‌شود.").setNegativeButton("انصراف",null).setPositiveButton("حذف کامل",(d,w)->{db.deleteTopic(t.id);load(null);}).show();}
 void backupSheet(){Dialog d=new Dialog(this);LinearLayout l=sheet(d);l.addView(Theme.text(this,"پشتیبان‌گیری و بازیابی",27,Theme.primary,Typeface.BOLD));TextView msg=Theme.text(this,"بکاپ JSON در Downloads یا هر مسیر دلخواه ذخیره می‌شود و هنگام بازیابی با داده‌های فعلی ادغام خواهد شد.",16,Theme.muted,Typeface.BOLD);msg.setPadding(0,Theme.dp(this,8),0,Theme.dp(this,16));l.addView(msg);Button ex=Theme.pill(this,"⬇ پشتیبان سریع",Theme.primary);Button im=Theme.pill(this,"⬆ بازیابی سریع",Theme.mix(Theme.primary,0xff000000,.1f));l.addView(ex,new LinearLayout.LayoutParams(-1,Theme.dp(this,58)));LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(-1,Theme.dp(this,58));ip.setMargins(0,Theme.dp(this,10),0,0);l.addView(im,ip);ex.setOnClickListener(v->{d.dismiss();Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"StudyNotes_Backup.json");startActivityForResult(i,EXP);});im.setOnClickListener(v->{d.dismiss();Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,IMP);});d.show();}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);try{if(c==RESULT_OK&&data!=null){Uri u=data.getData();if(r==EXP){OutputStream os=getContentResolver().openOutputStream(u);os.write(db.exportJson().toString(2).getBytes("UTF-8"));os.close();Theme.toast(this,"بکاپ ذخیره شد");}if(r==IMP){InputStream is=getContentResolver().openInputStream(u);ByteArrayOutputStream bo=new ByteArrayOutputStream();byte[]buf=new byte[4096];int n;while((n=is.read(buf))>0)bo.write(buf,0,n);is.close();db.importJson(new JSONObject(bo.toString("UTF-8")));load(null);Theme.toast(this,"بازیابی انجام شد");}}}catch(Exception e){Theme.toast(this,e.getMessage());}}
}
