package com.arena.studynotes;import android.app.*;import android.os.*;import android.content.*;import android.net.*;import android.graphics.*;import android.view.*;import android.webkit.*;import android.widget.*;import java.util.*;

public class NoteActivity extends Activity{DB db;long topicId;Topic topic;Note note;boolean tips=false;LinearLayout root,header;WebView web;
 @Override public void onCreate(Bundle b){super.onCreate(b);db=new DB(this);topicId=getIntent().getLongExtra("topic",1);topic=db.topic(topicId);long id=getIntent().getLongExtra("note",0);tips=getIntent().getBooleanExtra("tips",false);note=id>0?db.note(id):db.first(topicId,tips);draw();}
 @Override protected void onResume(){super.onResume();if(db!=null&&note!=null)note=db.note(note.id);if(root!=null)render();}
 void draw(){root=Theme.root(this);root.setPadding(Theme.dp(this,14),Theme.dp(this,8),Theme.dp(this,14),0);LinearLayout tb=new LinearLayout(this);tb.setGravity(Gravity.CENTER_VERTICAL);tb.setLayoutDirection(View.LAYOUT_RTL);root.addView(tb,new LinearLayout.LayoutParams(-1,Theme.dp(this,64)));String[] icons={"←","✎","＋","💡","☷","⌕"};for(String s:icons){ImageButton b=Theme.icon(this,s);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(Theme.dp(this,48),Theme.dp(this,48));p.setMargins(Theme.dp(this,4),0,Theme.dp(this,4),0);tb.addView(b,p);if(s.equals("←"))b.setOnClickListener(v->finish());if(s.equals("✎"))b.setOnClickListener(v->{if(note!=null)startActivity(new Intent(this,EditNoteActivity.class).putExtra("topic",topicId).putExtra("note",note.id));});if(s.equals("＋"))b.setOnClickListener(v->startActivity(new Intent(this,EditNoteActivity.class).putExtra("topic",topicId).putExtra("tips",tips)));if(s.equals("💡"))b.setOnClickListener(v->{tips=!tips;note=db.first(topicId,tips);render();});if(s.equals("☷"))b.setOnClickListener(v->tocSheet());if(s.equals("⌕"))b.setOnClickListener(v->searchSheet());}TextView name=Theme.text(this,topic==null?"":topic.title,18,Theme.text,Typeface.BOLD);name.setGravity(Gravity.CENTER);tb.addView(name,new LinearLayout.LayoutParams(0,-1,1));
  header=new LinearLayout(this);header.setOrientation(LinearLayout.VERTICAL);header.setPadding(Theme.dp(this,16),Theme.dp(this,14),Theme.dp(this,16),Theme.dp(this,14));header.setBackground(Theme.border(Theme.surface,Theme.stroke,Theme.dp(this,1),Theme.dp(this,24)));root.addView(header,new LinearLayout.LayoutParams(-1,-2));
  web=new WebView(this);web.setBackgroundColor(Theme.bg);web.getSettings().setJavaScriptEnabled(false);web.getSettings().setAllowFileAccess(true);web.getSettings().setAllowContentAccess(true);web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return handle(r.getUrl().toString());}@Override public boolean shouldOverrideUrlLoading(WebView v,String u){return handle(u);}});LinearLayout.LayoutParams wp=new LinearLayout.LayoutParams(-1,0,1);wp.setMargins(0,Theme.dp(this,10),0,0);root.addView(web,wp);render();}
 void render(){if(header==null)return;header.removeAllViews();if(note==null){empty();return;}LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setLayoutDirection(View.LAYOUT_RTL);header.addView(row);TextView ch=Theme.text(this,(tips?"نکته علمی • ":"")+safe(note.chapter),15,Theme.primary,Typeface.BOLD);row.addView(ch,new LinearLayout.LayoutParams(0,Theme.dp(this,28),1));ImageButton del=Theme.icon(this,"🗑");del.setImageDrawable(new Theme.TextDrawable("🗑",Theme.danger,Theme.dp(this,20)));row.addView(del,new LinearLayout.LayoutParams(Theme.dp(this,42),Theme.dp(this,42)));del.setOnClickListener(v->confirmDelete());TextView title=Theme.text(this,note.title,28,Theme.text,Typeface.BOLD);title.setPadding(0,Theme.dp(this,4),0,Theme.dp(this,8));header.addView(title);
  if(note.pdfName!=null&&!note.pdfName.isEmpty()){TextView pdf=Theme.text(this,"📄  "+note.pdfName+"   •   صفحه "+note.pdfPage,15,Theme.primary,Typeface.BOLD);pdf.setGravity(Gravity.CENTER);pdf.setPadding(Theme.dp(this,12),Theme.dp(this,8),Theme.dp(this,12),Theme.dp(this,8));pdf.setBackground(Theme.round(Theme.surface2,Theme.dp(this,16)));header.addView(pdf,new LinearLayout.LayoutParams(-1,Theme.dp(this,46)));pdf.setOnClickListener(v->openPdf());}
  web.setVisibility(View.VISIBLE);web.loadDataWithBaseURL(null,Markdown.html(note),"text/html","UTF-8",null);}
 String safe(String s){return s==null?"":s;}void empty(){header.addView(Theme.text(this,tips?"نکته‌ای ثبت نشده":"یادداشتی ثبت نشده",25,Theme.text,Typeface.BOLD));TextView m=Theme.text(this,tips?"اولین نکته علمی این موضوع را ایجاد کنید.":"اولین یادداشت این موضوع را ایجاد کنید.",16,Theme.muted,Typeface.BOLD);header.addView(m);Button add=Theme.pill(this,tips?"＋ درج اولین نکته":"＋ درج اولین یادداشت",tips?Theme.warning:Theme.primary);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,Theme.dp(this,58));ap.setMargins(0,Theme.dp(this,12),0,0);header.addView(add,ap);add.setOnClickListener(v->startActivity(new Intent(this,EditNoteActivity.class).putExtra("topic",topicId).putExtra("tips",tips)));web.setVisibility(View.GONE);} 
 boolean handle(String u){try{if(u.startsWith("note://")||u.startsWith("tip://")){long id=Long.parseLong(Uri.parse(u).getHost());Note n=db.note(id);if(n!=null){note=n;tips=n.tip;render();}return true;}if(u.startsWith("http")){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));return true;}}catch(Exception e){}return false;}void openPdf(){if(note.pdfUri!=null&&!note.pdfUri.isEmpty())startActivity(new Intent(this,PdfActivity.class).putExtra("uri",note.pdfUri).putExtra("page",note.pdfPage).putExtra("name",note.pdfName));else Theme.toast(this,"برای این کتاب PDF واقعی انتخاب نشده است");}
 void confirmDelete(){new AlertDialog.Builder(this).setTitle("حذف یادداشت؟").setMessage("«"+note.title+"» حذف شود؟").setNegativeButton("انصراف",null).setPositiveButton("حذف",(d,w)->{db.deleteNote(note.id);note=db.first(topicId,tips);render();}).show();}
 LinearLayout sheet(Dialog d){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(Theme.dp(this,22),Theme.dp(this,22),Theme.dp(this,22),Theme.dp(this,22));l.setBackground(Theme.round(Theme.surface,Theme.dp(this,28)));d.setContentView(l);return l;}
 void tocSheet(){Dialog d=new Dialog(this);ScrollView sv=new ScrollView(this);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(Theme.dp(this,20),Theme.dp(this,20),Theme.dp(this,20),Theme.dp(this,20));l.setBackground(Theme.round(Theme.surface,Theme.dp(this,26)));sv.addView(l);d.setContentView(sv);l.addView(Theme.text(this,tips?"فهرست نکات علمی":"فهرست یادداشت‌های درسی",27,Theme.primary,Typeface.BOLD));String ch="";for(Note n:db.notes(topicId,tips,null)){if(!Objects.equals(ch,n.chapter)){ch=n.chapter;TextView c=Theme.text(this,ch,20,Theme.text,Typeface.BOLD);c.setPadding(0,Theme.dp(this,16),0,Theme.dp(this,6));l.addView(c);}TextView row=Theme.text(this,(n.tip?"💡 ":"🔖 ")+n.title,18,Theme.primary,Typeface.BOLD);row.setPadding(Theme.dp(this,14),Theme.dp(this,12),Theme.dp(this,14),Theme.dp(this,12));row.setBackground(Theme.round(Theme.surface2,Theme.dp(this,16)));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,Theme.dp(this,58));rp.setMargins(0,Theme.dp(this,5),0,Theme.dp(this,5));l.addView(row,rp);row.setOnClickListener(v->{note=n;d.dismiss();render();});}d.show();}
 void searchSheet(){Dialog d=new Dialog(this);LinearLayout l=sheet(d);l.addView(Theme.text(this,"جستجوی پیشرفته",26,Theme.primary,Typeface.BOLD));EditText e=Theme.input(this,"عنوان، فصل یا متن یادداشت",false);l.addView(e,new LinearLayout.LayoutParams(-1,Theme.dp(this,66)));Button b=Theme.pill(this,"جستجو",Theme.primary);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,Theme.dp(this,58));bp.setMargins(0,Theme.dp(this,12),0,0);l.addView(b,bp);b.setOnClickListener(v->{ArrayList<Note> r=db.notes(topicId,tips,e.getText().toString().trim());if(r.isEmpty())Theme.toast(this,"نتیجه‌ای یافت نشد");else{note=r.get(0);d.dismiss();render();}});d.show();}
}
