package com.arena.studynotes;import android.app.*;import android.os.*;import android.content.*;import android.net.*;import android.graphics.*;import android.graphics.pdf.*;import android.os.ParcelFileDescriptor;import android.view.*;import android.widget.*;

public class PdfActivity extends Activity{PdfRenderer renderer;PdfRenderer.Page page;ImageView img;TextView count;int index=0;
 @Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout root=Theme.root(this);root.setPadding(Theme.dp(this,14),Theme.dp(this,8),Theme.dp(this,14),Theme.dp(this,14));root.addView(Theme.toolbar(this,getIntent().getStringExtra("name"),"←",v->finish(),"⛶",v->{}),new LinearLayout.LayoutParams(-1,Theme.dp(this,64)));
  LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);nav.setPadding(0,Theme.dp(this,8),0,Theme.dp(this,8));root.addView(nav,new LinearLayout.LayoutParams(-1,Theme.dp(this,76)));Button prev=Theme.pill(this,"‹",Theme.surface2);prev.setTextColor(Theme.text);Button next=Theme.pill(this,"›",Theme.surface2);next.setTextColor(Theme.text);count=Theme.text(this,"",22,Theme.primary,Typeface.BOLD);count.setGravity(Gravity.CENTER);nav.addView(prev,new LinearLayout.LayoutParams(Theme.dp(this,72),-1));nav.addView(count,new LinearLayout.LayoutParams(0,-1,1));nav.addView(next,new LinearLayout.LayoutParams(Theme.dp(this,72),-1));
  ScrollView sv=new ScrollView(this);img=new ImageView(this);img.setAdjustViewBounds(true);img.setBackgroundColor(Color.WHITE);sv.addView(img,new ScrollView.LayoutParams(-1,-2));root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));prev.setOnClickListener(v->show(index-1));next.setOnClickListener(v->show(index+1));open();}
 void open(){try{Uri u=Uri.parse(getIntent().getStringExtra("uri"));ParcelFileDescriptor pfd=getContentResolver().openFileDescriptor(u,"r");renderer=new PdfRenderer(pfd);show(Math.max(0,getIntent().getIntExtra("page",1)-1));}catch(Exception e){Theme.toast(this,"PDF باز نشد: "+e.getMessage());}}
 void show(int i){try{if(renderer==null||i<0||i>=renderer.getPageCount())return;if(page!=null)page.close();index=i;page=renderer.openPage(index);int w=getResources().getDisplayMetrics().widthPixels-Theme.dp(this,28);int h=(int)(w*(page.getHeight()/(float)page.getWidth()));Bitmap bm=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);bm.eraseColor(Color.WHITE);page.render(bm,null,null,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);img.setImageBitmap(bm);count.setText("صفحه "+(index+1)+" از "+renderer.getPageCount());}catch(Exception e){Theme.toast(this,e.getMessage());}}
 @Override protected void onDestroy(){try{if(page!=null)page.close();if(renderer!=null)renderer.close();}catch(Exception e){}super.onDestroy();}
}
