package com.arena.studynotes;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import java.text.*;import java.util.*;

/** Small dependency-free design system for a polished Persian RTL UI. */
public class Theme{
    static int bg,surface,surface2,text,muted,primary,primary2,stroke,danger,warning; static boolean dark;
    static void apply(Context c){dark=c.getSharedPreferences("s",0).getBoolean("dark",false);primary=0xff6f55c7;primary2=0xff8b6fed;danger=0xffe0443e;warning=0xffd8b400;if(dark){bg=0xff150f18;surface=0xff211827;surface2=0xff2c2233;text=0xfff7f2fb;muted=0xffc8bccf;stroke=0xff44394c;}else{bg=0xfffffbf8;surface=0xffffffff;surface2=0xfff4edf7;text=0xff20202a;muted=0xff716b78;stroke=0xffe4dae8;}}
    static int dp(Context c,float v){return (int)(v*c.getResources().getDisplayMetrics().density+0.5f);} static void rtl(View v){v.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);v.setTextDirection(View.TEXT_DIRECTION_RTL);} 
    static LinearLayout root(Activity a){apply(a);LinearLayout r=new LinearLayout(a);r.setOrientation(LinearLayout.VERTICAL);r.setBackgroundColor(bg);rtl(r);a.setContentView(r);return r;}
    static TextView text(Context c,String s,float sp,int color,int style){TextView v=new TextView(c);v.setText(s==null?"":s);v.setTextSize(sp);v.setTextColor(color);v.setTypeface(Typeface.DEFAULT,style);v.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);v.setIncludeFontPadding(true);rtl(v);return v;}
    static GradientDrawable round(int fill,float radius){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(radius);return g;} static GradientDrawable border(int fill,int st,int sw,float r){GradientDrawable g=round(fill,r);g.setStroke(sw,st);return g;}
    static GradientDrawable gradient(int c1,int c2,float r){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{c1,c2});g.setCornerRadius(r);return g;}
    static ImageButton icon(Context c,String s){ImageButton b=new ImageButton(c);b.setImageDrawable(new TextDrawable(s,primary,dp(c,26)));b.setBackground(round(dark?0x22ffffff:0x11000000,dp(c,18)));b.setPadding(dp(c,10),dp(c,10),dp(c,10),dp(c,10));return b;}
    static Button pill(Context c,String s,int color){Button b=new Button(c);b.setText(s);b.setTextSize(16);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setBackground(round(color,dp(c,22)));b.setPadding(dp(c,14),0,dp(c,14),0);rtl(b);return b;}
    static EditText input(Context c,String hint,boolean multi){EditText e=new EditText(c);e.setHint(hint);e.setTextSize(18);e.setTextColor(text);e.setHintTextColor(muted);e.setGravity((multi?Gravity.TOP:Gravity.CENTER_VERTICAL)|Gravity.RIGHT);e.setSingleLine(!multi);e.setMinLines(multi?6:1);e.setBackground(border(surface,stroke,dp(c,1),dp(c,16)));e.setPadding(dp(c,16),multi?dp(c,14):0,dp(c,16),multi?dp(c,14):0);rtl(e);return e;}
    static LinearLayout toolbar(Context c,String title,String leftIcon,View.OnClickListener left,String rightIcon,View.OnClickListener right){LinearLayout bar=new LinearLayout(c);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(c,16),dp(c,8),dp(c,16),dp(c,8));rtl(bar);if(leftIcon!=null){ImageButton l=icon(c,leftIcon);l.setOnClickListener(left);bar.addView(l,new LinearLayout.LayoutParams(dp(c,48),dp(c,48)));}TextView t=text(c,title,20,text,Typeface.BOLD);t.setGravity(Gravity.CENTER);bar.addView(t,new LinearLayout.LayoutParams(0,dp(c,56),1));if(rightIcon!=null){ImageButton r=icon(c,rightIcon);r.setOnClickListener(right);bar.addView(r,new LinearLayout.LayoutParams(dp(c,48),dp(c,48)));}return bar;}
    static void toast(Context c,String s){Toast.makeText(c,s,Toast.LENGTH_SHORT).show();}
    static int colorAt(int i){int[] a={0xff2f80ed,0xff27ae60,0xffeb5757,0xfff2a900,0xff9b27b0,0xff10a6b8,0xffd946ef,0xff607d8b};return a[Math.abs(i)%a.length];}
    static int soft(int c){return dark?mix(c,0xff000000,0.68f):mix(c,0xffffffff,0.86f);} static int mix(int a,int b,float t){int ar=Color.red(a),ag=Color.green(a),ab=Color.blue(a),br=Color.red(b),bg=Color.green(b),bb=Color.blue(b);return Color.rgb((int)(ar*(1-t)+br*t),(int)(ag*(1-t)+bg*t),(int)(ab*(1-t)+bb*t));}
    static void hideKeyboard(Activity a){try{((InputMethodManager)a.getSystemService(Context.INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(a.getWindow().getDecorView().getWindowToken(),0);}catch(Exception e){}}
    static class TextDrawable extends Drawable{String s;Paint p=new Paint(1);int color,size;TextDrawable(String s,int c,int z){this.s=s;this.color=c;this.size=z;p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);}public void draw(Canvas c){Rect b=getBounds();p.setColor(color);p.setTextSize(size);Paint.FontMetrics fm=p.getFontMetrics();c.drawText(s,b.centerX(),b.centerY()-(fm.ascent+fm.descent)/2,p);}public void setAlpha(int a){p.setAlpha(a);}public void setColorFilter(android.graphics.ColorFilter f){p.setColorFilter(f);}public int getIntrinsicWidth(){return size+20;}public int getIntrinsicHeight(){return size+20;}public int getOpacity(){return PixelFormat.TRANSLUCENT;}}
}
